<script type="text/javascript" src="<?php echo $this->getJsUrl('tagimages');?>/slider.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/highslide-full.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css') ?>/jquery.tag.css" media="all" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css') ?>/slider.css" media="all" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css') ?>/highslide.css" media="all" />
<?php  $collection = Mage::getBlockSingleton('tagimage/tagimage')->getCollection(); ?>
<?php if (count($collection) == 0) : ?>
<div class="note-msg" style="text-align: center"><h2><?php echo $this->__('There are no images matching the selection.') ?></h2></div>
<?php endif; ?>

<?php if (count($collection) > 0) : ?>
	<div class="pagination-container">
            <div class="pagination-left" id="image-categories">
                <div class="pagination-bottom">
                    <div  class="slider">
                        <?php foreach ($collection as $_item) : ?>
                        <?php  $category = Mage::registry('current_category')->getId(); ?>
                        <?php $C = explode(',',$_item->getCategories()); ?>
                            <?php if(in_array($category, $C)):?>
                               <dl>
                                    <dt>
                                        <div class="jTagOverlay">
                                           <?php echo Mage::getBlockSingleton('tagimage/tagimage')->getOverlayHtml($_item['tagimage_id']); ?>
                                        </div>
                                       <img src="<?php echo $this->helper('tagimage/image')->init($_item->getFile())->keepFrame(true)->resize(Mage::getSingleton('tagimage/config')->getWidht(),Mage::getSingleton('tagimage/config')->getHeight()); ?>" />
                                    </dt>
                                    <dd><span><?php echo $_item['label']; ?></span></dd>
                               </dl>
                             <?php endif; ?>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
    </div>

<?php endif; ?>


<script type="text/javascript">

		document.observe('dom:loaded', function () {
			$$('div.slider').each(function (e) {
				new SliderJS(e);
			});
		});
</script>

<script type="text/javascript">
             function showTag(id){
                 var box_height = $('table_'+id).getHeight();
                 var box_width = $('table_'+id).getWidth();
                 var slide_height = <?php echo $this->helper('tagimage')->settings('setheight'); ?>;
                 var slide_width   = <?php echo $this->helper('tagimage')->settings('setwidth'); ?>;
                 var top = $(id).getStyle('top').replace('px', '');
                 var left =  $(id).getStyle('left').replace('px', '');
                 if(parseInt(slide_height)<(parseInt(box_height)+parseInt(top))){
                     var _top_ = (parseInt(top)-parseInt(box_height));
                     if(_top_<0){
                         _top_ = 0;
                     }
                     $(id).setStyle({'top':_top_+'px'});
                 }
                 if(parseInt(slide_width)< (parseInt(box_width)+parseInt(left))){
                        var _left_ = (parseInt(left)-parseInt(box_width))-20;
                         $(id).setStyle({'left':_left_+'px'});
                 }

                 $('table_'+id).show();
                 $$('table.table_'+id).each(function(e){
                     e.show();
                 });
                 $(id).setOpacity(0.9999);

             };
             function hideTag(id){
                  $('table_'+id).hide();
                  $$('table.table_'+id).each(function(e){
                     e.hide();
                 });
                 $(id).setOpacity(0.001);

             };
</script>

<script type="text/javascript">
	hs.graphicsDir = '<?php echo $this->getSkinUrl('js/graphics/') ?>';
	hs.align = 'center';
	hs.transitions = ['expand', 'crossfade'];
	hs.wrapperClassName = 'dark borderless floating-caption';
	hs.fadeInOut = true;
	hs.dimmingOpacity = .75;
	hs.cacheAjax = false;


	// Add the controlbar
	if (hs.addSlideshow) hs.addSlideshow({
		//slideshowGroup: 'group1',
		interval: 5000,
		repeat: false,
		useControls: true,
		fixedControls: 'fit',
		overlayOptions: {
			opacity: .6,
			position: 'bottom center',
			hideOnMouseOut: true
		}
	});
</script>


<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
