<h4>Catalog Feed</h4>
<p style="width:650px">Go to your Settings in TurnTo Management area and enter:
<br>
 <i><?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) . 'turntocatalogfeed';?></i>
<br>
 in the <b>Catalog Feed Url:</b> input field.
<br>
<br>
 This will set up the automation of the catalog feed in order to keep you products up to date. </p>
<br>
<br>
<br>
To manually create a catalog feed press Generate to build a catalog feed. This feed can be downloaded and uploaded via the TurnTo management form.

<br>
<form id="cat_feed_form" name="cat_feed_form" method="post" action="<?php echo $this->getUrl('*/*/post') ?>">
	<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
	<input name="feed_type" type="hidden" value="catalog" />
	<table>
		<!--
		<tr>
			<td>Site Key:</td>
			<td><input id="siteKey" name="siteKey" type="text" /></td>
		</tr>
		<tr>
			<td>Auth Key:</td>
			<td><input id="authKey" name="authKey" type="text" /></td>
		</tr>
		-->
		<tr>
			<td></td>
			<td align="right">

<input id="submit" name="submit" value="Generate" type="submit" /></td>

		</tr>
	</table>




	
	<?php 
		$file = Mage::getBaseDir('media') . DS . 'turnto/catfeed.csv';
		
		if(file_exists($file)){
			echo '<br /><br /><a href="/media/turnto/catfeed.csv">Download catalog feed</a> - created '.date('m/d/Y G:i',filectime($file));
		}
	?>
</form>

