<h4>Overview</h4>
<p style="margin-top:10px;width:600px">

 
To install the Social Commerce Suite, first 
contact TurnTo to set up an account and get a license key for the cloud-based services, 
then setup your feeds and install the needed Javascript. TurnTo&#39;s support team will 
be happy to guide you through the steps.
<br>
<br>
A link to detailed documentation is below.  



</p>
<p style="margin-top:20px;width:600px">
	<b>To set up an account with Turnto, contact our Sales team via Email at 
	<a href="mailto:contact@turnto.com">contact@turnto.com</a>
	</b>
</p>
<h4 style="margin-top:20px">Feeds</h4>
<p style="margin-top:10px;width:650px">
1) Catalog Feed<br />
Go to your Settings in TurnTo Management area on the TurnTo site and enter <i><?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) . 'turntocatalogfeed'; ?></i> in the <b>Catalog Feed Url</b>: input field.
This will set up the automation of the catalog feed in order to keep you products up to date.
<br /><br />
2) Historical Batch Feed<br />
A one-time historical batch feed of past customers for populating TurnTo products in a text (tab delimited) format.  Feeds contain the information about your site's users and their activities on your site. Upload your magento generated historical feed in your TurnTo feed upload tab in the TurnTo settings area on the turnto website.<br />
</p>
<h4 style="margin-top:20px">Links</h4><p style="width:600px">Links to helpful information about TurnTo<br /><br />
<a href="http://www.turnto.com/docs/home/magentoconnectaccess" alt="TurnTo Documentation">TurnTo Documentation</a>
<br /><br />
<a href="http://www.turnto.com" alt="Moderation">TurnTo Moderation</a>
<br /><br />
<a href="http://www.turnto.com" alt="Reports">TurnTo Reports</a>
<br /><br />
<a href="http://www.turnto.com" alt="Settings">TurnTo Settings</a></p>
